const mongoose = require("mongoose")

const characterSchema = new mongoose.Schema({
  nome: String,
  jogador: Number,
  natureza: String,
  comportamento: String,
  essencia: String,
  tradicao: String,
  arete: Number,
  vontade: Number,
  quintessencia: Number,
  paradoxo: Number,
  antecedentes: Array,
  atributos: {
    forca: {valor:Number, especializacoes:[]},
    destreza: {valor:Number, especializacoes:[]},
    vigor: {valor:Number, especializacoes:[]},
    carisma: {valor:Number, especializacoes:[]},
    manipulacao: {valor:Number, especializacoes:[]},
    aparencia: {valor:Number, especializacoes:[]},
    percepcao: {valor:Number, especializacoes:[]},
    inteligencia: {valor:Number, especializacoes:[]},
    raciocinio: {valor:Number, especializacoes:[]},
  },
  habilidades: {
    talentos: {
      prontidao: {valor:Number, especializacoes:[]},
      esportes: {valor:Number, especializacoes:[]},
      consciencia: {valor:Number, especializacoes:[]},
      briga: {valor:Number, especializacoes:[]},
      esquiva: {valor:Number, especializacoes:[]},
      expressao: {valor:Number, especializacoes:[]},
      intimidacao: {valor:Number, especializacoes:[]},
      lideranca: {valor:Number, especializacoes:[]},
      manha: {valor:Number, especializacoes:[]},
      labia: {valor:Number, especializacoes:[]},
    },
    pericias: {
      oficios: {valor:Number, especializacoes:[]},
      conducao: {valor:Number, especializacoes:[]},
      etiqueta: {valor:Number, especializacoes:[]},
      armas_de_fogo: {valor:Number, especializacoes:[]},
      meditacao: {valor:Number, especializacoes:[]},
      armas_brancas: {valor:Number, especializacoes:[]},
      atuacao: {valor:Number, especializacoes:[]},
      furtividade: {valor:Number, especializacoes:[]},
      sobrevivencia: {valor:Number, especializacoes:[]},
      tecnologia: {valor:Number, especializacoes:[]},
    },
    conhecimentos: {
      academicos: {valor:Number, especializacoes:[]},
      computador: {valor:Number, especializacoes:[]},
      cosmologia: {valor:Number, especializacoes:[]},
      enigmas: {valor:Number, especializacoes:[]},
      investigacao: {valor:Number, especializacoes:[]},
      direito: {valor:Number, especializacoes:[]},
      linguistica: {valor:Number, especializacoes:[]},
      medicina: {valor:Number, especializacoes:[]},
      ocultismo: {valor:Number, especializacoes:[]},
      ciencias: {valor:Number, especializacoes:[]},
    },
  },
  esferas: {
    correspondencia: {valor:Number, especializacoes:[]},
    entropia: {valor:Number, especializacoes:[]},
    forcas: {valor:Number, especializacoes:[]},
    vida: {valor:Number, especializacoes:[]},
    mente: {valor:Number, especializacoes:[]},
    materia: {valor:Number, especializacoes:[]},
    primordio: {valor:Number, especializacoes:[]},
    espirito: {valor:Number, especializacoes:[]},
    tempo: {valor:Number, especializacoes:[]},
  },
})

module.exports = mongoose.model("Character", characterSchema)
